name: GroGuesser-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - biopython
  - jupyterlab>=3
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  # Tools
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # for projects
  - pytest
  # plotly
  # https://plotly.com/python/getting-started/
  - plotly
  # Requests
  # https://anaconda.org/conda-forge/requests
  - biopandas
  # MDanalys
  - mdanalysis
  # force installation from conda-forge since bioconda has an old version
  - vmd
  - pymol
  - loguru
  
  - pip:
    # watermark
    - watermark
    # streamlit
    - streamlit


