name: grodecoder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab>=3
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  # MDanalysis
  - mdanalysis
  # 3D molecular viewers
  - vmd
  - pymol-open-source
  # Logging
  - loguru
  - pip:
    # watermark: keep track of dependency versions
    - watermark


