name: grodecoder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab>=4
  - ipywidgets
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  - black
  - ruff
  # MD tools
  - mdanalysis
  - networkx
  - vmd
  - pymol-open-source
  # Logging
  - loguru
  - pip:
    # watermark: keep track of dependency versions
    - watermark


