name: GroDecoder-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab>=3
  # Linters and formaters
  - pycodestyle
  - pydocstyle
  - pylint
  # Tools
  # https://anaconda.org/conda-forge/requests
  - biopandas
  # MDanalys
  - mdanalysis
  # force installation from conda-forge since bioconda has an old version
  - vmd
  - pymol
  - loguru
  
  - pip:
    # watermark
    - watermark


